version: "3"

services:
    nginx:
        build:
            context: nginx
            args:
                - NGINX_VERSION=1.13.7-alpine
        image: nginx_certbot
        container_name: nginx_certbot1
        volumes:
            - /srv/docker_volumes/letsencrypt:/etc/letsencrypt
        ports:
            - "80:80"
            - "443:443"
        environment:
            - CERTBOT_DOMAIN=${CERTBOT_DOMAIN}
            - CERTBOT_EMAIL=${CERTBOT_EMAIL}
            - CERTBOT_WEBROOT=/usr/share/nginx/html
