version: "3"

services:
    nginx:
        build: nginx
        image: nginx_certbot
        container_name: nginx_certbot1
        volumes:
            - letsencrypt:/etc/letsencrypt
        ports:
            - "80:80"
            - "443:443"
        environment:
            - EMAIL=${EMAIL}
            - WEBROOT=/web/root
            - DOMAIN=example.com,www.example.com

volumes:
    letsencrypt:
        external: true
