version: "3"

services:
    nginx:
        build: nginx
        image: nginx_certbot
        container_name: nginx_certbot1
        volumes:
            - ../docker_volumes/letsencrypt:/etc/letsencrypt
        ports:
            - "80:80"
            - "443:443"
        environment:
            - NGINX_VERSION=1.13.6-alpine
            - CERTBOT_EMAIL=${CERTBOT_EMAIL}
            - CERTBOT_DOMAIN=${CERTBOT_DOMAIN}
            - CERTBOT_WEBROOT=/usr/share/nginx/html
